### ISSUE TITLE
Where are the binaries

### ISSUE THREAD

**Issue by moriyatiy** [hainesc/anchor#5]
Where are the binaries

**Comment by hainesc** [comment]
You can build yourself.

**Comment by moriyatiy** [comment]
> 
> 
> You can build yourself.

Seems to be missing some directories like bin

**Comment by hainesc** [comment]
Run `make anchor` and `make octopus`, and then you can find the binary in build/anchor/...

**Comment by moriyatiy** [comment]
> 
> 
> Run `make anchor` and `make octopus`, and then you can find the binary in build/anchor/...

ok，i got it
